name: Bot Quant Balanz

on:
  schedule:
    - cron: '*/15 * * * 1-5'
  workflow_dispatch: 

jobs:
  escanear_mercado:
    runs-on: ubuntu-latest
    
    # ¡ESTO ES LO NUEVO! Le damos permiso al bot para escribir en tu repositorio
    permissions:
      contents: write
      
    steps:
    - name: Descargar mi código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Instalar librerías
      run: |
        pip install pandas yfinance requests
        
    - name: Ejecutar Motor Cuantitativo
      run: python motor_247.py
      
    - name: Guardar estado de las alertas (Si alguna se cumplió)
      run: |
        git config --global user.name "Bot Cuantitativo"
        git config --global user.email "bot@quant.com"
        # Ignora errores si el CSV aún no existe en GitHub
        git add data/alertas_trading.csv || true
        git diff --quiet && git diff --staged --quiet || (git commit -m "Actualización automática de estado de alerta" && git push)